name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          ssh root@${{ secrets.DIGITALOCEAN_IP }} <<EOF
          cd /var/www/hngx-stage2-fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart fastapi
          EOF
