name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH Key
        uses: shimataro/ssh-key-action@v2  # Easier way to set up SSH key
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just accept' # Or add the line from step 5 above

      - name: Deploy to DigitalOcean
        run: |
          ssh root@${{ secrets.DIGITALOCEAN_IP }} "
            cd /var/www/hngx-stage2-fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi  # Use sudo for systemctl
          "